
###
POST http://localhost:3000/user/register 
content-type: application/json

{
    "name":"deneme",
    "surname":"deneme",
    "userName":"deneme",
    "password":"deneme"
}

###
POST http://localhost:3000/user/login
content-type: application/json

{
    "userName":"deneme",
    "password":"deneme"
}

###
GET  http://localhost:3000/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYTJiMzY1MDUzMzkzY2U3NDU2M2QiLCJpYXQiOjE2Njg1MjU0NDAsImV4cCI6MTY2ODUyOTA0MH0.T5EUhycFo8u7uX9pgpEyFr05lkX4s9l1LKy-TniO3Nc

###
DELETE  http://localhost:3000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

###
PATCH   http://localhost:3000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M
content-type: application/json

{
    "name":"updated",
    "surname":"updated",
    "userName":"updated2",
    "password":"updated"
}

###
PATCH   http://localhost:3000/user/changePassword
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

{
    "password":"611094"
}


###
POST http://localhost:3000/notebooks
content-type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

{
    "language":"ENGLISH"
}

###
GET http://localhost:3000/notebooks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

###
DELETE http://localhost:3000/notebooks/6373adcb92eb8a325f544f69
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVkODNjMDg3YTU4MGJiZjVlYjcwYjQiLCJpYXQiOjE2Njc5OTcxMTMsImV4cCI6MTY2ODAwMDcxM30.PbkaFgLCpNJ-J37mkSR3rvD5YuhYP_lYTQgDKF7xmNo

###
POST  http://localhost:3000/cards/6373adcb92eb8a325f544f69
content-type: application/json
Authorization:   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

{
    "type":"VERB",
    "phrase":"to try",
    "definition": "to try",
    "tabooOne":"try",
    "tabooTwo":"try",
    "tabooThree":"try"
}

###
GET  http://localhost:3000/cards/getAll/6373adcb92eb8a325f544f69
Authorization:   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M


###
GET  http://localhost:3000/cards/6373adf492eb8a325f544f72
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

###
PATCH   http://localhost:3000/cards/6373adf492eb8a325f544f72
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

{
    "phrase": "to go",
    "definition": "to move from somewhere to another place",
    "tabooOne": "commute",
    "tabooTwo": "drive",
    "tabooThree": "change"
}

###
DELETE http://localhost:3000/cards/6373adf492eb8a325f544f72
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M
