
###
POST http://localhost:3000/user/register 
content-type: application/json

{
    "name":"deneme",
    "userName":"deneme",
    "email":"deneme@gmail.com",
    "password":"611094"
}

###
POST http://localhost:3000/user/login
content-type: application/json

{
    "userName":"deneme",
    "password":"deneme"
}

###
POST http://localhost:3000/user/forgot-password
content-type: application/json

{
    "email":"syldrmkaya@gmail.com"
}

###
GET  http://localhost:3000/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgwZjYzZDYyZmFiOTEwZDA1Mzk3ZWYiLCJpYXQiOjE2NjkzOTYwODksImV4cCI6MTY2OTM5OTY4OX0.rtfb1mQyPhqqO_CC7HmsnCOJBO80GZQwlXrn9eXmkDw

###
DELETE  http://localhost:3000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

###
PATCH   http://localhost:3000/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgwZjYzZDYyZmFiOTEwZDA1Mzk3ZWYiLCJpYXQiOjE2NjkzOTYwODksImV4cCI6MTY2OTM5OTY4OX0.rtfb1mQyPhqqO_CC7HmsnCOJBO80GZQwlXrn9eXmkDw
content-type: application/json

{
    "name":"deneme",
    "userName":"deneme"
}

###
PATCH   http://localhost:3000/user/changePassword
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgwZjYzZDYyZmFiOTEwZDA1Mzk3ZWYiLCJpYXQiOjE2NjkzOTYwODksImV4cCI6MTY2OTM5OTY4OX0.rtfb1mQyPhqqO_CC7HmsnCOJBO80GZQwlXrn9eXmkDw

{
    "password":"deneme"
}


###
POST http://localhost:3000/notebooks
content-type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgwZjYzZDYyZmFiOTEwZDA1Mzk3ZWYiLCJpYXQiOjE2NjkzOTYwODksImV4cCI6MTY2OTM5OTY4OX0.rtfb1mQyPhqqO_CC7HmsnCOJBO80GZQwlXrn9eXmkDw

{
    "language":"ENGLISH"
}

###
GET http://localhost:3000/notebooks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzgwZjYzZDYyZmFiOTEwZDA1Mzk3ZWYiLCJpYXQiOjE2NjkzOTYwODksImV4cCI6MTY2OTM5OTY4OX0.rtfb1mQyPhqqO_CC7HmsnCOJBO80GZQwlXrn9eXmkDw

###
DELETE http://localhost:3000/notebooks/6373adcb92eb8a325f544f69
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVkODNjMDg3YTU4MGJiZjVlYjcwYjQiLCJpYXQiOjE2Njc5OTcxMTMsImV4cCI6MTY2ODAwMDcxM30.PbkaFgLCpNJ-J37mkSR3rvD5YuhYP_lYTQgDKF7xmNo

###
POST  http://localhost:3000/cards/637e036b159f9ce3c5fc7dee
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdjOGQxZTJmNDM3MzI5MDIzZTZhOGQiLCJpYXQiOjE2NjkyMDI3NjIsImV4cCI6MTY2OTIwNjM2Mn0.fc4AlOBKUq834ZlJMwiNk8TKf0akiKBn9YDalm6Gs0k

{
    "type":"VERB1",
    "phrase":"to try10",
    "definition": "to try",
    "tabooOne":"try",
    "tabooTwo":"try",
    "tabooThree":"try"
}

###
GET  http://localhost:3000/cards/getAll/6373adcb92eb8a325f544f69
Authorization:   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M



###
GET  http://localhost:3000/cards/getRandom/637e036b159f9ce3c5fc7dee
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdjOGQxZTJmNDM3MzI5MDIzZTZhOGQiLCJpYXQiOjE2NjkyMDM0NzksImV4cCI6MTY2OTIwNzA3OX0.UgN6bUynl5YwhIpPCWncPPzhBtCLfh8FDPHNAOeD6S4


###
GET  http://localhost:3000/cards/6373adf492eb8a325f544f72
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

###
PATCH   http://localhost:3000/cards/6373adf492eb8a325f544f72
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M

{
    "phrase": "to go",
    "definition": "to move from somewhere to another place",
    "tabooOne": "commute",
    "tabooTwo": "drive",
    "tabooThree": "change"
}

###
DELETE http://localhost:3000/cards/6373adf492eb8a325f544f72
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzczYWQ5ZTkyZWI4YTMyNWY1NDRmNWMiLCJpYXQiOjE2Njg1MjU0NzIsImV4cCI6MTY2ODUyOTA3Mn0.3HrIXfQwCJVZHfIycfEuiU5AVgVYgHW16Ip5jNNuE_M
